spring:
  application:
    name: PAYMENT-SERVICE
  security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:8080/realms/RentACarMicroservice/protocol/openid-connect/certs
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
server:
  port: 0